---
# defaults file for zfs-rescue

osrelease: buster
osreleasebp: buster-backports
drive1: nvme0n1
drive2: nvme1n1
diskbyid1: nvme-KXG60ZNV512G_TOSHIBA_106S10CJT9LM
diskbyid2: nvme-KXG60ZNV512G_TOSHIBA_106S10COT9LM
root_password: test1234
#format_zfs: true